pipeline {
  agent any
  environment {
    AWS_ACCOUNT_ID="664776724646"
    AWS_DEFAULT_REGION="us-east-1"	
    IMAGE_REPO_NAME="chitti"
    IMAGE_TAG="${env.BUILD_ID}"
    REPOSITORY_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}"
		registryCredential = "ecr-aws"
  }
  stages {
    stage('Sonar Analysis'){
      steps {
        withSonarQubeEnv('localsonar'){
          sh '''
           echo $PATH
            mvn clean verify sonar:sonar \
            -Dsonar.projectKey=mypetclinic -f $WORKSPACE/spring-petclinic/pom.xml
          '''
        }     
      }
    }
    stage('Sonar Quality Gate'){
      steps{
        timeout(time: 5, unit: 'MINUTES') {
           waitForQualityGate abortPipeline: true
        }
      }
    }
    stage('Build Image'){
      steps {     
        //sh "docker build $WORKSPACE/spring-petclinic -t petc:local -f $WORKSPACE/spring-petclinic/Dockerfile"
        script {
          dockerImage = docker.build("${IMAGE_REPO_NAME}:${IMAGE_TAG}","${WORKSPACE}/spring-petclinic/")
        }
      }
    }
    // Uploading Docker images into AWS ECR
    stage('Pushing to ECR') {
      steps{  
        script {
          docker.withRegistry("https://" + REPOSITORY_URI, "ecr:${AWS_DEFAULT_REGION}:" + registryCredential) {
          dockerImage.push()
          }
        }
      }
    }
  }
}
