pipeline {
  agent any
  tools {
    maven 'MAVEN'
  }
  stages{
    stage ('Initialize') {
       steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
       }
    }
    stage('Sonar Analysis'){
      steps {
        withSonarQubeEnv('localsonar'){
          sh '''
            mvn clean verify sonar:sonar \
            -Dsonar.projectKey=mypetclinic 
          '''
        }
      }
    }
    stage('Build'){
      steps {                
        sh "mvn clean package -DSkipTests=true -f $WORKSPACE/spring-petclinic/pom.xml"
        archive 'target/*.jar'
      }
    }
  }
}
