apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-petclinic-deployment
  namespace: eks-petclinic-app
  labels:
    app: eks-petclinic-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-petclinic-app
  template:
    metadata:
      labels:
        app: eks-petclinic-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: petclinic
        image: 815528447289.dkr.ecr.us-east-1.amazonaws.com/chitti:10
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
