apiVersion: v1
kind: Service
metadata:
  name: eks-lb-service
  namespace: eks-petclinic-app
  labels:
    app: eks-petclinic-app
spec:
  type: LoadBalancer
  selector:
    app: eks-petclinic-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
